#!/usr/bin/env python3
"""
Generate docs/knowledge/repos.yaml from docs/repos/*.md

Each repo page has a table with Field/Value rows. We extract:
  - Title (H1 heading)
  - GitHub URL
  - Language
  - Stars
  - Last updated
  - Description (first non-empty line after the H1 / table)

Run: python3 scripts/generate-repos-manifest.py
Output: docs/knowledge/repos.yaml
"""

import os
import re
from datetime import date
from pathlib import Path

REPOS_DIR = Path(__file__).parent.parent / "docs" / "repos"
OUTPUT = Path(__file__).parent.parent / "docs" / "knowledge" / "repos.yaml"

SKIP_FILES = {"index.md"}
SKIP_STEMS = {".synthesis"}


def extract_field(lines, field_name):
    """Extract a value from markdown table rows like | Field | Value |"""
    pattern = re.compile(r"^\|\s*\*?\*?" + re.escape(field_name) + r"\*?\*?\s*\|\s*(.*?)\s*\|")
    for line in lines:
        m = pattern.match(line)
        if m:
            return m.group(1).strip()
    return None


def extract_github_url(text):
    """Extract bare GitHub URL from markdown link or plain URL."""
    # Match URL up to whitespace, ), ], or end — handles both bare URLs and markdown links
    m = re.search(r"https://github\.com/[\w.\-/]+", text)
    return m.group(0) if m else None


def parse_repo_page(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return None

    # Title from first H1
    title = None
    for line in lines:
        m = re.match(r"^#\s+(.+)", line)
        if m:
            title = m.group(1).strip()
            break
    if not title:
        title = path.stem

    github_raw = extract_field(lines, "GitHub")
    github_url = extract_github_url(github_raw) if github_raw else None
    language = extract_field(lines, "Language")
    stars_raw = extract_field(lines, "Stars")
    updated = extract_field(lines, "Last updated")

    stars = None
    if stars_raw:
        m = re.search(r"\d+", stars_raw)
        if m:
            stars = int(m.group(0))

    # Slug from filename
    slug = path.stem

    return {
        "id": slug,
        "title": title,
        "github": github_url,
        "language": language,
        "stars": stars,
        "updated": updated,
    }


def main():
    repos = []
    for p in sorted(REPOS_DIR.glob("*.md")):
        if p.name in SKIP_FILES or p.stem in SKIP_STEMS:
            continue
        entry = parse_repo_page(p)
        if entry:
            repos.append(entry)

    today = date.today().isoformat()

    lines = [
        "# wiki.cantara.no — repository index (auto-generated)",
        "# DO NOT EDIT — regenerated by .github/workflows/kcp-manifests.yml",
        f"# Repositories: {len(repos)} | Generated: {today}",
        'version: "0.14"',
        "",
        "id: repos",
        "parent: https://wiki.cantara.no/knowledge.yaml",
        "",
        "discovery:",
        "  provenance: canonical",
        "  confidence: high",
        "  staleness_days: 7",
        "  generated_by: scripts/generate-repos-manifest.py",
        "",
        "signing:",
        "  scheme: ed25519",
        "  scope: this-manifest",
        "  public_key: https://wiki.cantara.no/.well-known/kcp-signing-key.pub",
        "  signature: https://wiki.cantara.no/knowledge/repos.yaml.sig",
        "",
        f"repo_count: {len(repos)}",
        "",
        "repos:",
    ]

    for r in repos:
        lines.append(f"  - id: {r['id']}")
        lines.append(f"    title: {json_str(r['title'])}")
        if r["github"]:
            lines.append(f"    github: {r['github']}")
        if r["language"]:
            lines.append(f"    language: {json_str(r['language'])}")
        if r["stars"] is not None:
            lines.append(f"    stars: {r['stars']}")
        if r["updated"]:
            lines.append(f"    updated: {json_str(r['updated'])}")
        lines.append(f"    url: https://wiki.cantara.no/repos/{r['id']}/")
        lines.append("")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(repos)} repos.")


def json_str(s):
    """Quote a string value for YAML (simple quoting)."""
    if not s:
        return '""'
    if any(c in s for c in ':{}[]|>&*!,#?-\'"@`'):
        escaped = s.replace('"', '\\"')
        return f'"{escaped}"'
    return s


if __name__ == "__main__":
    main()
